#!/usr/bin/env python3
"""Reproduce native saddle tables from the WLRI PE and matching C decompile.

Only the two pure offset functions and fixed-frame selector are compiled in a
local harness. No game executable is run. Requires Python, a C compiler and gofmt.
"""
import argparse
import hashlib
from pathlib import Path
import re
import struct
import subprocess
import tempfile


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--exe", type=Path, required=True)
    parser.add_argument("--decompile", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    binary = args.exe.read_bytes()
    source = args.decompile.read_text()
    pe = struct.unpack_from("<I", binary, 60)[0]
    count = struct.unpack_from("<H", binary, pe + 6)[0]
    optional_size = struct.unpack_from("<H", binary, pe + 20)[0]
    base = struct.unpack_from("<I", binary, pe + 24 + 28)[0]
    sections = [struct.unpack_from("<IIII", binary, pe + 24 + optional_size + i * 40 + 8) for i in range(count)]

    def read(address, length):
        for _, virtual, size, offset in sections:
            if base + virtual <= address and address + length <= base + virtual + size:
                return binary[offset + address - base - virtual:offset + address - base - virtual + length]
        raise ValueError(f"PE address outside raw sections: {address:x}")

    functions = []
    for name in ("FUN_0040cbb4", "FUN_0040e4b4", "FUN_0040f0d4"):
        start = source.index("// Function: " + name)
        end = source.index("// Function:", start + 12)
        body = source[start:end]
        # Delphi's adjacent stack locals must not depend on host C layout.
        body = body.replace("FUN_00012d10(&local_1c,8,0);", "local_1c = local_18 = 0;")
        body = body.replace("FUN_00012d10(&local_14,8,0);", "local_14 = local_10 = 0;")
        # Instrument the default branch so tables full of zeros are retained.
        body = body.replace("switchD_0040ccdb_caseD_3e9:\n", "switchD_0040ccdb_caseD_3e9:\n  native_table = 0;\n")
        # The native text-file fallback writes two adjacent locals; disabled in
        # this harness because the Go runtime reads the exported file itself.
        functions.append(body)
    code = "\n".join(functions)
    declarations = []
    for symbol in sorted(set(re.findall(r"DAT_([0-9a-f]{8})", code))):
        values = struct.unpack("<45i", read(int(symbol, 16), 180))
        declarations.append(f"static int32_t table_{symbol}[] = {{{','.join(map(str, values))}}};")
        declarations.append(f"#define DAT_{symbol} (*(char *)table_{symbol})")
    harness = """#include <stdint.h>
#include <stdio.h>
typedef uint32_t undefined4;
typedef uint32_t uint;
static int native_table;
static char FUN_0040ee64(undefined4 p, int id) { return 0; }
static uint FUN_0040eed0(undefined4 p, int id) { return 18; }
static uint FUN_0040ef5c(undefined4 p, int id) { return 0; }
static void FUN_0040efe8(undefined4 p,int id,int body,undefined4 *out,int facing) {}
""" + "\n".join(declarations) + code + """
int main(void) {
 for(int id=1000;id<2000;id++) {
  int sit = id==0x413 || id==0x416 || id==0x462 || id==0x468 || id==0x4a8 || id==0x4ba || id==0x51b || (id>=0x51e && id<=0x520) || id==0x524 || id==0x52c || id==0x53e || id==0x61a || id==0x625 || id==0x679 || id==0x74b;
  int fixed = FUN_0040f0d4(0,id);
  undefined4 offsets[32][2], move[32][2];
  native_table=1;
  for(int body=1;body<=4;body++) for(int dir=0;dir<8;dir++) {
   int i=(body-1)*8+dir;
   FUN_0040cbb4(0,body,(sit?46:18)+dir,offsets[i],id);
   FUN_0040e4b4(0,body,(sit?46:18)+dir,move[i],id);
  }
  if(!native_table && !sit && !fixed) continue;
  printf("%d %d %d %d",id,sit,fixed,native_table);
  for(int i=0;i<32;i++) printf(" %d %d %d %d",(int32_t)offsets[i][0],(int32_t)offsets[i][1],(int32_t)move[i][0],(int32_t)move[i][1]);
  puts("");
 }
}
"""
    with tempfile.TemporaryDirectory(prefix="wlo-mount-") as temporary:
        root = Path(temporary)
        (root / "tables.c").write_text(harness)
        subprocess.run(["cc", "-std=c99", "-O0", str(root / "tables.c"), "-o", str(root / "tables")], check=True)
        rows = subprocess.check_output([str(root / "tables")], text=True).splitlines()
    output = ["// Code generated by tools/decompile/mount_tables.py; DO NOT EDIT.",
              "// WLRI aLogin.exe SHA256: " + hashlib.sha256(binary).hexdigest(),
              "// FUN_0040cbb4 / FUN_0040e4b4 / FUN_0040f0d4; original authored integer tables.",
              "package role", "", "type nativeMountEntry struct { Placement MountPlacement; HasOffsets bool }",
              "var nativeMountPlacements = map[uint16]nativeMountEntry{"]
    for row in rows:
        numbers = list(map(int, row.split()))
        identifier, sit, fixed, authored = numbers[:4]
        output.append(f"{identifier}: {{HasOffsets: {str(bool(authored)).lower()}, Placement: MountPlacement{{Sit: {str(bool(sit)).lower()}, FixedFirst: {str(bool(fixed)).lower()},")
        for field, axis in (("Stand", 0), ("Move", 2)):
            if field == "Move" and not any(numbers[4+i*4+axis+j] for i in range(32) for j in range(2)):
                continue
            output.append(field + ": [4][8][2]int{")
            for body in range(4):
                pairs = ["{%d,%d}" % tuple(numbers[4+(body*8+d)*4+axis:6+(body*8+d)*4+axis]) for d in range(8)]
                output.append("{" + ",".join(pairs) + "},")
            output.append("},")
        output.append("}},")
    output.append("}\n")
    args.output.write_text("\n".join(output))
    subprocess.run(["gofmt", "-w", str(args.output)], check=True)
    print(f"Wrote {len(rows)} native mount definitions to {args.output}")


if __name__ == "__main__":
    main()
